package com.itheima.dao.cargo;

import com.itheima.domain.cargo.Factory;
import com.itheima.domain.cargo.FactoryExample;

import java.util.List;

public interface IFactoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int insertSelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    List<Factory> selectByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    Factory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Factory record);
}